### ISSUE TITLE
Conformance tool rejects inband event definition in MPD

### ISSUE THREAD

**Issue by tlohmar** [Dash-Industry-Forum/Conformance-Software#176] opened 2016-10-21 16:58 UTC
An error was throws, because there was `<InbandEventStream schemeIdUri="urn:mpeg:dash:event:2012" />` in an adaptation set element.

```
Line:Col[23:69]:cvc-complex-type.2.4.a: Invalid content was found starting with element 'InbandEventStream'. One of '{"urn:mpeg:dash:schema:mpd:2011":Representation}' is expected.
MPD validation not successful - DASH is not valid!
```

**Comment by AdithyanIlangovan** [comment] 2016-10-27 13:51
@tlohmar Thanks for reporting the issue.
Could you provide your .mpd that actually caused this problem?

I used the following sample .mpd with InbandEventStream at the adaptationSet element level. 
The .mpd passed without any conformance errors.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<!--Single content continuing at the period boundary.-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" minBufferTime="PT1.500000S" type="static" mediaPresentationDuration="PT0H9M54.00S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
  <Period id="0" duration="PT250S">
    <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="24" par="16:9">
	  <InbandEventStream schemeIdUri="urn:mpeg:dash:event:2012" />	
      <Representation id="1" mimeType="video/mp4" codecs="avc1.4d401f" width="1280" height="720" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="980104">
        <SegmentTemplate timescale="12288" presentationTimeOffset="1024" duration="24576" media="BBB_720_1M_video_$Number$.mp4" startNumber="1" initialization="BBB_720_1M_video_init.mp4" />
      </Representation>
      <Representation id="2" mimeType="video/mp4" codecs="avc1.4d401f" width="1280" height="720" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="1950145">
        <SegmentTemplate timescale="12288" presentationTimeOffset="1024" duration="24576" media="BBB_720_2M_video_$Number$.mp4" startNumber="1" initialization="BBB_720_2M_video_init.mp4"></SegmentTemplate>
      </Representation>
      <Representation id="3" mimeType="video/mp4" codecs="avc1.4d401f" width="1280" height="720" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="3893089">
        <SegmentTemplate timescale="12288" presentationTimeOffset="1024" duration="24576" media="BBB_720_4M_video_$Number$.mp4" startNumber="1" initialization="BBB_720_4M_video_init.mp4" />
      </Representation>
    </AdaptationSet>
    <AdaptationSet segmentAlignment="true">
      <Representation id="4" mimeType="audio/mp4" codecs="mp4a.40.29" audioSamplingRate="48000" startWithSAP="1" bandwidth="33434">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
        <SegmentTemplate timescale="48000" duration="94175" media="BBB_32k_$Number$.mp4" startNumber="1" initialization="BBB_32k_init.mp4" />
      </Representation>
    </AdaptationSet>
  </Period>
  <Period id="1" duration="PT344S">
    <AdaptationSet segmentAlignment="true" maxWidth="1280" maxHeight="720" maxFrameRate="24" par="16:9">
	  <InbandEventStream schemeIdUri="urn:mpeg:dash:event:2012" />	
      <Representation id="1" mimeType="video/mp4" codecs="avc1.4d401f" width="1280" height="720" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="980104">
        <SegmentTemplate timescale="12288" presentationTimeOffset="3073024" duration="24576" media="BBB_720_1M_video_$Number$.mp4" startNumber="126" initialization="BBB_720_1M_video_init.mp4" />
      </Representation>
      <Representation id="2" mimeType="video/mp4" codecs="avc1.4d401f" width="1280" height="720" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="1950145">
        <SegmentTemplate timescale="12288" presentationTimeOffset="3073024" duration="24576" media="BBB_720_2M_video_$Number$.mp4" startNumber="126" initialization="BBB_720_2M_video_init.mp4" />
      </Representation>
      <Representation id="3" mimeType="video/mp4" codecs="avc1.4d401f" width="1280" height="720" frameRate="24" sar="1:1" startWithSAP="1" bandwidth="3893089">
        <SegmentTemplate timescale="12288" presentationTimeOffset="3073024" duration="24576" media="BBB_720_4M_video_$Number$.mp4" startNumber="126" initialization="BBB_720_4M_video_init.mp4" />
      </Representation>
    </AdaptationSet>
    <AdaptationSet segmentAlignment="true">
      <Representation id="4" mimeType="audio/mp4" codecs="mp4a.40.29" audioSamplingRate="48000" startWithSAP="1" bandwidth="33434">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
        <SegmentTemplate timescale="48000" presentationTimeOffset="11964416" duration="94175" media="BBB_32k_$Number$.mp4" startNumber="126" initialization="BBB_32k_init.mp4" />
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

**Comment by tlohmar** [comment] 2016-10-27 17:25
Here you go. Both, Shaka and DASH.js play the content...

<?xml version='1.0' encoding='UTF-8'?>
<MPD availabilityStartTime="2016-10-14T07:15:26.682000Z" minBufferTime="PT2.00S" profiles="urn:mpeg:dash:profile:isoff-live:2011" publishTime="2016-10-14T07:15:27.010000Z" mediaPresentationDuration="PT120.00S" type="static"
	xmlns="urn:mpeg:dash:schema:mpd:2011"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd">
	<Period id="1" start="PT0.00S">
		<AdaptationSet codecs="avc1.640028" contentType="video" maxBandwidth="613221" maxFrameRate="30" maxHeight="1080" maxWidth="1920" mimeType="video/mp4">
			<SegmentTemplate duration="15" initialization="$RepresentationID$/Header.m4s" media="$RepresentationID$/$Number$.m4s" presentationTimeOffset="1" startNumber="1" timescale="15" />
			<Representation bandwidth="613221" frameRate="30" height="1080" id="video" width="1920" />
			<InbandEventStream schemeIdUri="urn:mpeg:dash:event:2012" />
		</AdaptationSet>
		<AdaptationSet audioSamplingRate="48000" codecs="mp4a.40.2" contentType="audio" lang="und" maxBandwidth="129228" mimeType="audio/mp4">
			<SegmentTemplate duration="1" initialization="$RepresentationID$/Header.m4s" media="$RepresentationID$/$Number$.m4s" presentationTimeOffset="0" startNumber="1" timescale="1" />
			<Representation bandwidth="129228" id="audio" />
		</AdaptationSet>
	</Period>
</MPD>

**Comment by AdithyanIlangovan** [comment] 2016-10-28 12:29
Thanks for the reply.
If I modify your provide .mpd to:
``` xml
<?xml version='1.0' encoding='UTF-8'?>
<MPD availabilityStartTime="2016-10-14T07:15:26.682000Z" minBufferTime="PT2.00S" profiles="urn:mpeg:dash:profile:isoff-live:2011" publishTime="2016-10-14T07:15:27.010000Z" mediaPresentationDuration="PT120.00S" type="static"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd">
    <Period id="1" start="PT0.00S">
        <AdaptationSet codecs="avc1.640028" contentType="video" maxBandwidth="613221" maxFrameRate="30" maxHeight="1080" maxWidth="1920" mimeType="video/mp4">
            <InbandEventStream schemeIdUri="urn:mpeg:dash:event:2012" />
            <SegmentTemplate duration="15" initialization="$RepresentationID$/Header.m4s" media="$RepresentationID$/$Number$.m4s" presentationTimeOffset="1" startNumber="1" timescale="15" />
            <Representation bandwidth="613221" frameRate="30" height="1080" id="video" width="1920" />
        </AdaptationSet>
        <AdaptationSet audioSamplingRate="48000" codecs="mp4a.40.2" contentType="audio" lang="und" maxBandwidth="129228" mimeType="audio/mp4">
            <SegmentTemplate duration="1" initialization="$RepresentationID$/Header.m4s" media="$RepresentationID$/$Number$.m4s" presentationTimeOffset="0" startNumber="1" timescale="1" />
            <Representation bandwidth="129228" id="audio" />
        </AdaptationSet>
    </Period>
</MPD>
```

i.e, if I just move the `InbandEventStream` element to the first level in adaptationSet level. Then, your provided .mpd conforms well.

I am currently going to check, if the DASH standard places any restriction on the sequence/location of `InbandEventStream` element.

**Comment by AdithyanIlangovan** [comment] 2016-10-28 13:46
Related to my earlier comment.
I found this in DASH-IF standard (See Annex B in ISO/IEC 23009-1:2014).

```xml
  <!-- Representation base (common attributes and elements) -->
  <xs:complexType name="RepresentationBaseType">
    <xs:sequence>
      <xs:element name="FramePacking" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="AudioChannelConfiguration" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="ContentProtection" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="EssentialProperty" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="SupplementalProperty" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="InbandEventStream" type="EventStreamType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
```

and 

```xml

  <!-- Adaptation Set -->
  <xs:complexType name="AdaptationSetType">
    <xs:complexContent>
      <xs:extension base="RepresentationBaseType">
        <xs:sequence>
          <xs:element name="Accessibility" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="Role" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="Rating" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="Viewpoint" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="ContentComponent" type="ContentComponentType" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="BaseURL" type="BaseURLType" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="SegmentBase" type="SegmentBaseType" minOccurs="0"/>
          <xs:element name="SegmentList" type="SegmentListType" minOccurs="0"/>
          <xs:element name="SegmentTemplate" type="SegmentTemplateType" minOccurs="0"/>
          <xs:element name="Representation" type="RepresentationType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
```

what this essentially means is that in the `adaptationSet` type, you need to follow an order of elements:

1. `InbandEventStream`
2. `SegmentTemplate`
3. `Representation` 
and so on

The conformance does this correctly. The problem is with the .mpd.

Closing this issue.
If you have any questions/problems, please reopen.

**Closed by AdithyanIlangovan** 2016-10-28 13:46 UTC
