### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/Conformance-Software#235] opened 2017-10-09 08:59 UTC
Input URL: https://wowza03.cdr.nl/EncAudio/mp4:KAX8252-0001.m4a/manifest.mpd?TOKENCHUNK=VE9LRU49MjU2MjY5MTY4MzI3OTk2MTY1NCZET01BSU49d3d3LmRldi1tdXppZWt3ZWIubmw=

Result is error in MPD validation:

```
IOException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Expected result: actual validation.

MPD opens fine in Chrome for me. HTTPS certificate store on server out of date maybe?

**Comment by waqarz** [comment] 2017-10-09 13:40
@niteeshbhat please see https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ could this be fixed by updating java?

**Comment by niteeshbhat** [comment] 2017-10-10 10:32
java is updated.. (jre-8u144) but doesnt help.. 
The above link says the solution is to add the server certificate.
I cannot add the certificate of the site to the java certicates as dashif.org isn't a secure connection.

**Comment by niteeshbhat** [comment] 2017-10-12 08:25
The input URL without query string , i.e .. https://wowza03.cdr.nl/EncAudio/mp4:KAX8252-0001.m4a/manifest.mpd 
works now.!!
With query string -TOKENCHUNK=VE9LRU49MjU2MjY5MTY4MzI3OTk2MTY1NCZET01BSU49d3d3LmRldi1tdXppZWt3ZWIubmw=
there is new error -
SAXException: The processing instruction target matching "[xX][mM][lL]" is not allowed.
Validation not successful!

Closing this certificate path issue here.. and opening a new issue for this.

**Closed by niteeshbhat** 2017-10-12 08:25 UTC

**Comment by waqarz** [comment] 2017-10-12 08:40
> java is updated.. (jre-8u144) but doesnt help..

@niteeshbhat thanks for this, but I see from this website the issue is caused by a website updating its certificate:

>> We experienced this issue when a server changed their HTTPS SSL certificate, and our older version >> of Java did not recognize the root certificate authority (CA).
>>
>> If you can access the HTTPS URL in your browser then it is possible to update Java to recognize the root CA.

From conformance software side, we are just responsible to periodically update Java. If this does not address the issue, we should just leave it there. Its an issue with the website and Java, not to be solved here. Thanks again for fixing this though.
