### ISSUE TITLE
Validator fails to process video (nothing happens, just stays at 0%)

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/Conformance-Software#143] opened 2016-07-25 15:54 UTC
Video: http://wowzaec2demo.streamlock.net/live/bigbuckbunny/manifest_mvlist.mpd

If you enter this video into http://dashif.org/conformance.html nothing happens, it never shows any results. "MPD conformance only" checkbox state makes no difference.

I waited a few minutes. Did not check if waiting for longer fixes it (the manifest is pretty small with only 10 segments total; not very likely I expect).

Related: https://github.com/Dash-Industry-Forum/dash.js/issues/1507

**Comment by waqarz** [comment] 2016-07-26 07:06
The issue is that SegmentList is not supported, the validator should notify this as a minimum. Closing this one and opening it here: https://github.com/Dash-Industry-Forum/Conformance-Software/issues/144

**Closed by waqarz** 2016-07-26 07:06 UTC
