### ISSUE TITLE
Online Validator Server Crashed?

### ISSUE THREAD

**Issue by richardbushell** [Dash-Industry-Forum/Conformance-Software#131] opened 2016-03-17 16:50 UTC
I'm sure you know already, but I think the Online Validator Server may have crashed and needs restarting? Just get 'Processing...' at the moment.

**Comment by waqarz** [comment] 2016-03-17 16:59
Thanks for reporting, its running now but unfortunately I am not 100% sure what cuased the crash or how to reproduce it, will keep an eye on this.

**Comment by waqarz** [comment] 2016-03-18 14:40
Yup, thats going to be one tricky bug. Actually it does not crash, rather their seems to be some permissions problem of write access on the server intermittently. We try to find which update caused this and roll back. For now I clear again the permissions issue

**Comment by richardbushell** [comment] 2016-03-22 16:04
Same again, please clear/reset.
Any joy tracking down the root problem?

**Comment by waqarz** [comment] 2016-03-23 11:04
We think we've found the problem, doing testing now

**Comment by waqarz** [comment] 2016-03-23 11:07
The problem is orphan sessions left on the server, tests started but interrupted somehow. Now adding robustness against that.

**Comment by joywelt** [comment] 2016-03-23 13:16
The orphan sessions appear when users submit invalid MPD files (wrong path etc.), which caused this problem. It's fixed in my new commit. We will make it online soon.

**Closed** 2016-03-23 13:16 UTC

**Comment by waqarz** [comment] 2016-03-23 17:06
I have put an updated version that should fix this. Seems to be working fine, if the issue reappears please reopen.
